### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by daimazhnenana** [YifanXu74/MQ-Det#12]
作者您好，在按照readme执行训练mq-groundingdino-t.yaml时，出现keyerror: positive map。求助，谢谢！

**Comment by YifanXu74** [comment]
Hi @daimazhnenana,
You can try using the latest version of code. If the problem remains, could you provide detailed error information and steps to reproduce this error? Meanwhile, current code only supports GroundingDINO for modulated training and finetuning-free evaluation.

**Comment by daimazhnenana** [comment]
对应的error: Traceback (most recent call last):
  File "/root/MQ/tools/train_net.py", line 477, in <module>
    main()
  File "/root/MQ/tools/train_net.py", line 469, in main
    model = train(cfg=cfg,
  File "/root/MQ/tools/train_net.py", line 225, in train
    do_train(
  File "/root/MQ-Det/maskrcnn_benchmark/engine/trainer.py", line 123, in do_train
    loss_dict = model(images, targets)
  File "/root/.local/conda/envs/mq/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/MQ-Det/groundingdino_new/models/GroundingDINO/groundingdino.py", line 465, in forward
    positive_map = kw['positive_map']
KeyError: 'positive_map'   
运行的命令：python -m torch.distributed.launch --nproc_per_node=2 tools/train_net.py --config-file configs/pretrain/mq-groundingdino-t.yaml --use-tensorboard OUTPUT_DIR 'OUTPUT/MQ-GROUNDINGDINO-TINY-COCO/'

**Comment by YifanXu74** [comment]
看你的运行命令，是用了自己的COCO数据集进行训练吗？如果是的话，需要确保数据集的名字中含有"_grounding"，并且在代码中加入对应的list。见：
https://github.com/YifanXu74/MQ-Det/blob/611e176b016bf6777ccf21172a734b8bb0654f3a/maskrcnn_benchmark/config/paths_catalog.py#L387-L394

**Comment by daimazhnenana** [comment]
谢谢通了
