### ISSUE TITLE
Conduct modulated pretraining报错

### ISSUE THREAD

**Issue by Swaggeraqua** [YifanXu74/MQ-Det#41]
你好，
请问我在预训练时，遇到如下错误，我不知道如何解决，同时我也不太理解这段代码的作用。
此外，Extract vision queries起到了什么作用。对应模型的哪一部分。
Conduct modulated pretraining是训练GCP吗
我很好奇，我用自定义的数据集训练，那这个数据集在如上2个步骤都用到了吗，分别起了什么作用？
如果我的任务是小样本目标检测，那么Modulated Training后还需要微调吗

希望您能帮忙解答，非常感谢

Traceback (most recent call last):
  File "/home/junyi.zhou/MQ-Det-main/tools/train_net.py", line 482, in <module>
    main()
  File "/home/junyi.zhou/MQ-Det-main/tools/train_net.py", line 474, in main
    model = train(cfg=cfg,
  File "/home/junyi.zhou/MQ-Det-main/tools/train_net.py", line 226, in train
    do_train(
  File "/home/junyi.zhou/MQ-Det-main/maskrcnn_benchmark/engine/trainer.py", line 122, in do_train
    loss_dict = model(images, targets, captions=captions, positive_map=positive_map, greenlight_map = greenlight_map)
  File "/home/junyi.zhou/anaconda3/envs/dinov2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/junyi.zhou/MQ-Det-main/maskrcnn_benchmark/modeling/detector/generalized_vl_rcnn_new.py", line 348, in forward
    batched_labels_in_caption=[t.get_field('labels_in_caption') for t in targets]
  File "/home/junyi.zhou/MQ-Det-main/maskrcnn_benchmark/modeling/detector/generalized_vl_rcnn_new.py", line 348, in <listcomp>
    batched_labels_in_caption=[t.get_field('labels_in_caption') for t in targets]
  File "/home/junyi.zhou/MQ-Det-main/maskrcnn_benchmark/structures/bounding_box.py", line 61, in get_field
    return self.extra_fields[field]
KeyError: 'labels_in_caption'

**Comment by TinyQi** [comment]
我也遇到这个情况了，请问你怎么解决的呀？
